siteName: Edit Raleigh
siteDescription: Propose. Discuss. Improve. Raleigh.
emailContact: reid.serozi@gmail.com
twitterURL:
discordURL:
githubURL: https://github.com/reidserozi/city-discuit
substackURL:

isDevelopment: true
hmacSecret: <insert-your-secret-here>
noLogToFile: false
csrfOff: false

addr: :8080
sessionCookieName: SID

# MariaDB configuration:
dbAddr: 127.0.0.1 # Required
dbUser: discuit # Required
dbPassword: discuit # Required
dbName: discuit # Required

# ReCAPTCHA or hCaptcha secret and site-key:
captchaSecret:
captchaSiteKey:
disableRateLimits: false

# TLS certificate key-pair paths:
certFile:
keyFile:

defaultFeedSort: hot
disableForumCreation: true
forumCreationReqPoints: 10
maxForumsPerUser: 10
imagesFolderPath: "images"

# Stytch authentication (optional):
stytchProjectID: project-test-b014f033-dee9-452c-ac73-52da7ab2769f
stytchSecret: secret-test-G9xVzb0YqVI0eR0XRALpsyWdQ7Mqnas5Adw=
stytchEnvironment: test
