version: "3"

services:
  discuit:
    build:
      context: .
      dockerfile: docker/Dockerfile.amd64
    image: edit-raleigh:latest
    restart: unless-stopped
    expose:
      - "80"
    environment:
      DISCUIT_ADDR: ":80"
      DISCUIT_SITE_NAME: "Edit Raleigh"
      DISCUIT_SESSION_COOKIE_NAME: "DSID"
      DISCUIT_REDIS_ADDRESS: "127.0.0.1:6379"
      DISCUIT_FORUM_CREATION_REQ_POINTS: "10"
      DISCUIT_MAX_FORUMS_PER_USER: "10"
    volumes:
      - discuit-db:/var/lib/mysql
      - discuit-redis:/var/lib/redis
      - discuit-images:/app/images
    env_file: .env

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /app/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - discuit

volumes:
  discuit-db:
  discuit-redis:
  discuit-images:
  caddy-data:
  caddy-config:
