ALTER TABLE posts ADD COLUMN latitude DECIMAL(10, 8) NULL DEFAULT NULL;
ALTER TABLE posts ADD COLUMN longitude DECIMAL(11, 8) NULL DEFAULT NULL;
ALTER TABLE posts ADD COLUMN location_name VARCHAR(255) NULL DEFAULT NULL;
